version: "3"
services:
  nginx:
    image: registry:5000/todowebcalendarapp/nginx:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    depends_on:
      - api
    environment:
      SERVICE_PORTS: 80
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 1024
      KEEPALIVE_TIMEOUT: 65
      GZIP: "on"
      BACKEND_HOST: todo_app_api:8080
      BACKEND_MAX_FAILES: 3
      BACKEND_FAIL_TIMEOUT: 10s
      SERVER_PORT: 80
      SERVER_NAME: localhost
      LOG_STDOUT: "true"
    networks:
      - todoapp

  api:
    image: registry:5000/todowebcalendarapp/todoapi:latest 
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    networks:
      - todoapp

networks:
  todoapp:
    external: true
